#!/bin/bash
#COLORS
#https://misc.flogisoft.com/bash/tip_colors_and_formatting

#TEXT COLORS
DegaultT="\e[39m"
BlackT="\e[30m"
RedT="\e[31m"
GreenT="\e[32m"
YellowT="\e[33m"
BlueT="\e[34m"
MagentaT="\e[35m"
CyanT="\e[36m"
GrayLT="\e[37m"
GrayDT="\e[90m"
RedLT="\e[91m"
GreenLT="\e[92m"
YellowLT="\e[93m"
BlueLT="\e[94m"
MagentaLT="\e[95m"
CyanLT="\e[96m"
WhiteLT="\e[97m"

#BACKGROUND COLORS


RedB="\e[41m"
RedLB="\e[101m"
GreenB="\e[42m"
GreenLB="\e[102m"
YellowB="\e[43m"
YellowLB="\e[103m"
BlueB="\e[44m"
BlueLB="\e[104m"
CyanB="\e[46m"
CyanLB="\e[106m"
GrayLB="\e[47m"
GrayDB="\e[100m"
MagentaB="\e[45m"
MagentaLB="\e[105m"
WhiteB="\e[107m"

reserAllColors="\e[0m"
bold="\e[1m"
underlined="\e[4m"
blink="\e[5m"

#ECHO DIFFERENT TEXT COLORS
echo ""
echo "DIFFERENT TEXT COLORS"
echo -e "${DefaultT} This is an example of DefaultT"
echo -e "${BlackT} This is an example of BlackT"
echo -e "${RedT} This is an example of RedT"
echo -e "${RedLT} This is an example of RedLT"
echo -e "${GreenT} This is an example of GreenT"
echo -e "${GreenLT} This is an example of GreenLT"
echo -e "${YellowT} This is an example of YellowT"
echo -e "${YellowLT} This is an example of YellowLT"
echo -e "${BlueT} This is an example of BlueT"
echo -e "${BlueLT} This is an example of BlueLT"
echo -e "${MagentaT} This is an example of MagentaT"
echo -e "${MagentaLT} This is an example of MagentaLT"
echo -e "${CyanT} This is an example of CyanT"
echo -e "${CyanLT} This is an example of CyanLT"
echo -e "${GrayLT} This is an example of GrayLT"
echo -e "${GrayDT} This is an example of GrayDT"
echo -e "${WhiteLT} This is an example of WhiteLT"


#ECHO DIFFERENT TEXT COLORS BOLD
echo ""
echo "DIFFERENT TEXT COLORS BOLD"
echo -e "${DefaultT}${bold} This is an example of DefaultT Bold"
echo -e "${RedT}${bold} This is an example of RedT Bold"
echo -e "${GreenT}${bold} This is an example of GreenT Bold"
echo -e "${YellowT}${bold} This is an example of YellowT Bold"
echo -e "${BlueT}${bold} This is an example of BlueT Bold"
echo -e "${MagentaT}${bold} This is an example of MagentaT Bold"
echo -e "${CyanT}${bold} This is an example of CyanT Bold"
echo -e "${GrayDT}${bold} This is an example of GrayDT Bold"
echo -e "${WhiteLT}${bold} This is an example of WhiteLT Bold"

#ECHO DIFFERENT TEXT COLORS BOLD UNDERLINED
echo ""
echo "DIFFERENT TEXT COLORS BOLD UNDERLINED"
echo -e "${DefaultT}${bold}${underlined} This is an example of DefaultT Bold Underlined"
echo -e "${RedT}${bold}${underlined} This is an example of RedT Bold Underlined"
echo -e "${GreenT}${bold}${underlined} This is an example of GreenT Bold Underlined"
echo -e "${YellowT}${bold}${underlined} This is an example of YellowT Bold Underlined"
echo -e "${BlueT}${bold}${underlined} This is an example of BlueT Bold Underlined"
echo -e "${MagentaT}${bold}${underlined} This is an example of MagentaT Bold Underlined"
echo -e "${CyanT}${bold}${underlined} This is an example of CyanT Bold Underlined"
echo -e "${GrayDT}${bold}${underlined} This is an example of GrayDT Bold Underlined"
echo -e "${WhiteLT}${bold}${underlined} This is an example of WhiteLT Bold Underlined"

#ECHO DIFFERENT TEXT COLORS BOLD UNDERLINED BLINK
echo ""
echo "DIFFERENT TEXT COLORS BOLD UNDERLINED BLINK"
echo -e "${DefaultT}${bold}${underlined}${blink} This is an example of DefaultT Bold Underlined Blink"
echo -e "${RedT}${bold}${underlined}${blink} This is an example of RedT Bold Underlined Blink"
echo -e "${GreenT}${bold}${underlined}${blink} This is an example of GreenT Bold Underlined Blink"
echo -e "${YellowT}${bold}${underlined}${blink} This is an example of YellowT Bold Underlined Blink"
echo -e "${BlueT}${bold}${underlined}${blink} This is an example of BlueT Bold Underlined Blink"
echo -e "${MagentaT}${bold}${underlined}${blink} This is an example of MagentaT Bold Underlined Blink"
echo -e "${CyanT}${bold}${underlined}${blink} This is an example of CyanT Bold Underlined Blink"
echo -e "${GrayDT}${bold}${underlined}${blink} This is an example of GrayDT Bold Underlined Blink"
echo -e "${WhiteLT}${bold}${underlined}${blink} This is an example of WhiteLT Bold Underlined Blink"


#ECHO DIFFERENT BACKGROUND COLORS
echo ""
echo "DIFFERENT BACKGROUND COLORS"
echo -e "${DefaultT}${bold}${underlined}${blink} This is an example of DefaultT Bold Underlined Blink"
echo -e "${RedT}${bold}${underlined}${blink} This is an example of RedT Bold Underlined Blink"
echo -e "${GreenT}${bold}${underlined}${blink} This is an example of GreenT Bold Underlined Blink"
echo -e "${YellowT}${bold}${underlined}${blink} This is an example of YellowT Bold Underlined Blink"
echo -e "${BlueT}${bold}${underlined}${blink} This is an example of BlueT Bold Underlined Blink"
echo -e "${MagentaT}${bold}${underlined}${blink} This is an example of MagentaT Bold Underlined Blink"
echo -e "${CyanT}${bold}${underlined}${blink} This is an example of CyanT Bold Underlined Blink"
echo -e "${GrayDT}${bold}${underlined}${blink} This is an example of GrayDT Bold Underlined Blink"
echo -e "${WhiteLT}${bold}${underlined}${blink} This is an example of WhiteLT Bold Underlined Blink"


#ECHO DIFFERENT BACKGROUND COLORS
echo ""
echo -e "${reserAllColors}DIFFERENT BACKGROUND COLORS"
echo -e "${DefaultB} This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB} This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB} This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB} This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB} This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB} This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB} This is an example of YellowT BACKGROUND${reserAllColors}"
echo -e "${YellowLB} This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB} This is an example of BlueT BACKGROUND${reserAllColors}"
echo -e "${BlueLB} This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB} This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB} This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB} This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB} This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB} This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB} This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB} This is an example of WhiteLT BACKGROUND${reserAllColors}"




#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH DEFAULT BOLD UNDERLINED
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH DEFAULT BOLD UNDERLINED"
echo -e "${DefaultB}${DefaultT}${bold}${underlined}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${DefaultT}${bold}${underlined}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${DefaultT}${bold}${underlined}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${DefaultT}${bold}${underlined}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${DefaultT}${bold}${underlined}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${DefaultT}${bold}${underlined}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${DefaultT}${bold}${underlined}This is an example of YellowT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${DefaultT}${bold}${underlined}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${DefaultT}${bold}${underlined}This is an example of BlueT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${DefaultT}${bold}${underlined}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${DefaultT}${bold}${underlined}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${DefaultT}${bold}${underlined}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${DefaultT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${DefaultT}${bold}${underlined}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${DefaultT}${bold}${underlined}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${DefaultT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${DefaultT}${bold}${underlined}This is an example of WhiteLT BACKGROUND${reserAllColors}"


#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH RED BOLD UNDERLINED
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH RED BOLD UNDERLINED"
echo -e "${DefaultB}${RedT}${bold}${underlined}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${RedT}${bold}${underlined}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${RedT}${bold}${underlined}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${RedT}${bold}${underlined}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${RedT}${bold}${underlined}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${RedT}${bold}${underlined}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${RedT}${bold}${underlined}This is an example of YellowT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${RedT}${bold}${underlined}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${RedT}${bold}${underlined}This is an example of BlueT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${RedT}${bold}${underlined}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${RedT}${bold}${underlined}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${RedT}${bold}${underlined}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${RedT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${RedT}${bold}${underlined}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${RedT}${bold}${underlined}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${RedT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${RedT}${bold}${underlined}This is an example of WhiteLT BACKGROUND${reserAllColors}"

#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH RED BOLD UNDERLINED BLINK
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH RED BOLD UNDERLINED BLINK"
echo -e "${DefaultB}${GreenT}${bold}${underlined}${blink}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${GreenT}${bold}${underlined}${blink}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${GreenT}${bold}${underlined}${blink}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${GreenT}${bold}${underlined}${blink}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${GreenT}${bold}${underlined}${blink}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${GreenT}${bold}${underlined}${blink}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${GreenT}${bold}${underlined}${blink}This is an example of YellowT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${GreenT}${bold}${underlined}${blink}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${GreenT}${bold}${underlined}${blink}This is an example of BlueT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${GreenT}${bold}${underlined}${blink}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${GreenT}${bold}${underlined}${blink}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${GreenT}${bold}${underlined}${blink}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${GreenT}${bold}${underlined}${blink}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${GreenT}${bold}${underlined}${blink}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${GreenT}${bold}${underlined}${blink}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${GreenT}${bold}${underlined}${blink}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${GreenT}${bold}${underlined}${blink}This is an example of WhiteLT BACKGROUND${reserAllColors}"



#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH YELLOW BOLD UNDERLINED
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH YELLOW BOLD UNDERLINED"
echo -e "${DefaultB}${YellowT}${bold}${underlined}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${YellowT}${bold}${underlined}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${YellowT}${bold}${underlined}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${YellowT}${bold}${underlined}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${YellowT}${bold}${underlined}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${YellowT}${bold}${underlined}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${YellowT}${bold}${underlined}This is an example of YellowT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${YellowT}${bold}${underlined}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${YellowT}${bold}${underlined}This is an example of BlueT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${YellowT}${bold}${underlined}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${YellowT}${bold}${underlined}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${YellowT}${bold}${underlined}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${YellowT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${YellowT}${bold}${underlined}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${YellowT}${bold}${underlined}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${YellowT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${YellowT}${bold}${underlined}This is an example of WhiteLT BACKGROUND${reserAllColors}"





#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH BLUE BOLD UNDERLINED
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH BLUE BOLD UNDERLINED"
echo -e "${DefaultB}${BlueT}${bold}${underlined}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${BlueT}${bold}${underlined}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${BlueT}${bold}${underlined}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${BlueT}${bold}${underlined}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${BlueT}${bold}${underlined}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${BlueT}${bold}${underlined}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${BlueT}${bold}${underlined}This is an example of BlueT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${BlueT}${bold}${underlined}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${BlueT}${bold}${underlined}This is an example of BlueT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${BlueT}${bold}${underlined}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${BlueT}${bold}${underlined}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${BlueT}${bold}${underlined}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${BlueT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${BlueT}${bold}${underlined}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${BlueT}${bold}${underlined}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${BlueT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${BlueT}${bold}${underlined}This is an example of WhiteLT BACKGROUND${reserAllColors}"


#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH MAGENTA BOLD UNDERLINED
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH MAGENTA BOLD UNDERLINED"
echo -e "${DefaultB}${MagentaT}${bold}${underlined}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${MagentaT}${bold}${underlined}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${MagentaT}${bold}${underlined}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${MagentaT}${bold}${underlined}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${MagentaT}${bold}${underlined}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${MagentaT}${bold}${underlined}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${MagentaT}${bold}${underlined}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${MagentaT}${bold}${underlined}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${MagentaT}${bold}${underlined}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${MagentaT}${bold}${underlined}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${MagentaT}${bold}${underlined}This is an example of MagentaT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${MagentaT}${bold}${underlined}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${MagentaT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${MagentaT}${bold}${underlined}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${MagentaT}${bold}${underlined}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${MagentaT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${MagentaT}${bold}${underlined}This is an example of WhiteLT BACKGROUND${reserAllColors}"


#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH MAGENTA BOLD UNDERLINED
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH MAGENTA BOLD UNDERLINED"
echo -e "${DefaultB}${CyanT}${bold}${underlined}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${CyanT}${bold}${underlined}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${CyanT}${bold}${underlined}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${CyanT}${bold}${underlined}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${CyanT}${bold}${underlined}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${CyanT}${bold}${underlined}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${CyanT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${CyanT}${bold}${underlined}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${CyanT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${CyanT}${bold}${underlined}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${CyanT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${CyanT}${bold}${underlined}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${CyanT}${bold}${underlined}This is an example of CyanT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${CyanT}${bold}${underlined}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${CyanT}${bold}${underlined}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${CyanT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${CyanT}${bold}${underlined}This is an example of WhiteLT BACKGROUND${reserAllColors}"


#ECHO DIFFERENT COMBINATION OF BACKGROUND WITH MAGENTA BOLD UNDERLINED
echo ""
echo -e "${reserAllColors}DIFFERENT COMBINATION OF BACKGROUND WITH MAGENTA BOLD UNDERLINED"
echo -e "${DefaultB}${GrayDT}${bold}${underlined}This is an example of DefaultT BACKGROUND${reserAllColors}"
echo -e "${BlackB}${GrayDT}${bold}${underlined}This is an example of BlackT BACKGROUND${reserAllColors}"
echo -e "${RedB}${GrayDT}${bold}${underlined}This is an example of RedT BACKGROUND${reserAllColors}"
echo -e "${RedLB}${GrayDT}${bold}${underlined}This is an example of RedLT BACKGROUND${reserAllColors}"
echo -e "${GreenB}${GrayDT}${bold}${underlined}This is an example of GreenT BACKGROUND${reserAllColors}"
echo -e "${GreenLB}${GrayDT}${bold}${underlined}This is an example of GreenLT BACKGROUND${reserAllColors}"
echo -e "${YellowB}${GrayDT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${YellowLB}${GrayDT}${bold}${underlined}This is an example of YellowLT BACKGROUND${reserAllColors}"
echo -e "${BlueB}${GrayDT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${BlueLB}${GrayDT}${bold}${underlined}This is an example of BlueLT BACKGROUND${reserAllColors}"
echo -e "${MagentaB}${GrayDT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${MagentaLB}${GrayDT}${bold}${underlined}This is an example of MagentaLT BACKGROUND${reserAllColors}"
echo -e "${CyanB}${GrayDT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${CyanLB}${GrayDT}${bold}${underlined}This is an example of CyanLT BACKGROUND${reserAllColors}"
echo -e "${GrayLB}${GrayDT}${bold}${underlined}This is an example of GrayLT BACKGROUND${reserAllColors}"
echo -e "${GrayDB}${GrayDT}${bold}${underlined}This is an example of GrayDT BACKGROUND${reserAllColors}"
echo -e "${WhiteLB}${GrayDT}${bold}${underlined}This is an example of WhiteLT BACKGROUND${reserAllColors}"
